"""Pramana — curated Indian medical domain allowlist.

Three bands, from the editorial review:

  A (enabled)   Live-ready. Apex bodies, national programmes, ICMR journals.
  B (disabled)  Plausible but unverified — ICMR institutes, specialty journals
                and societies. Enable individually after checking the site
                actually hosts citable guidance.
  C (disabled)  Unvetted. State health departments, institutional protocols,
                smaller societies. High failure rate expected; several may not
                resolve at all.

Only `enabled` domains are sent to the search API, so B and C are recorded
here for one-click enabling in Admin → Allowed websites without widening what
the product can cite today.

AYUSH domains are deliberately DISABLED: the PRD scopes the corpus to
modern/allopathic sources and excludes traditional medicine from the MVP
(mixing evidentiary traditions on one answer surface is a trust problem).
Enable only if an explicitly-labelled AYUSH mode ships.
"""

STATE_NOTE = "State health department — state guidance; may differ from national policy."
INST_NOTE = "Institutional protocol; local practice, not national policy."

# (domain, trust_note, enabled)
SEED_DOMAINS: list[tuple[str, str, bool]] = [
    # ---------------- Band A — live-ready ----------------
    ("icmr.gov.in", "Indian Council of Medical Research — apex national research & guideline body.", True),
    ("main.icmr.nic.in", "ICMR legacy host — Standard Treatment Workflows & guideline archive.", True),
    ("mohfw.gov.in", "Ministry of Health & Family Welfare — primary ministry domain.", True),
    ("main.mohfw.gov.in", "MoHFW — official policy & Standard Treatment Guidelines.", True),
    ("clinicalestablishments.mohfw.gov.in", "MoHFW Clinical Establishments Act — STGs by specialty.", True),
    ("dghs.mohfw.gov.in", "Directorate General of Health Services — apex technical advisory body.", True),
    ("cdsco.gov.in", "Central Drugs Standard Control Organisation — drug approvals & safety.", True),
    ("nhm.gov.in", "National Health Mission — programme guidelines & training modules.", True),
    ("ncdc.gov.in", "National Centre for Disease Control — outbreak, AMR & communicable disease.", True),
    ("ncdc.mohfw.gov.in", "NCDC under DGHS — surveillance & outbreak documentation.", True),
    ("ihip.mohfw.gov.in", "Integrated Health Information Platform — national disease surveillance.", True),
    ("tbcindia.gov.in", "National TB Elimination Programme — TB diagnosis & treatment guidelines.", True),
    ("ncdirindia.org", "National Centre for Disease Informatics & Research — cancer registry.", True),
    ("ijmr.org.in", "Indian Journal of Medical Research — ICMR peer-reviewed journal.", True),
    ("nmji.in", "National Medical Journal of India — peer-reviewed, AIIMS-affiliated.", True),
    ("indianpediatrics.net", "Indian Pediatrics — IAP official journal.", True),
    ("niirncd.icmr.org.in", "ICMR National Institute of Health Research, Jodhpur — NCD research.", True),
    ("jiaps.com", "Journal of Indian Association of Pediatric Surgeons.", True),
    ("ncahp.abdm.gov.in", "National Commission for Allied & Healthcare Professions.", True),
    ("nmc.org.in", "National Medical Commission — medical education & practice regulation.", True),
    ("pharmacopoeia.org.in", "Indian Pharmacopoeia Commission — IP monographs & pharmacovigilance.", True),
    ("naco.gov.in", "National AIDS Control Organisation — HIV testing & ART guidelines.", True),
    ("nvbdcp.gov.in", "National Centre for Vector Borne Diseases Control — malaria, dengue, kala-azar.", True),
    ("nhp.gov.in", "National Health Portal — MoHFW health information.", True),
    ("nin.res.in", "National Institute of Nutrition (ICMR) — dietary guidelines & RDA.", True),
    ("nihfw.ac.in", "National Institute of Health & Family Welfare — public health training.", True),
    ("ctri.nic.in", "Clinical Trials Registry — India.", True),
    ("nppaindia.nic.in", "National Pharmaceutical Pricing Authority — drug price control.", True),
    ("fssai.gov.in", "Food Safety & Standards Authority of India.", True),
    ("notto.mohfw.gov.in", "National Organ & Tissue Transplant Organisation.", True),
    ("nabh.co", "NABH — hospital accreditation standards.", True),
    ("nhsrcindia.org", "National Health Systems Resource Centre — health systems guidance.", True),
    ("nha.gov.in", "National Health Authority — Ayushman Bharat implementation.", True),
    ("pmjay.gov.in", "PM-JAY — treatment package guidelines & rates.", True),
    ("cghs.gov.in", "Central Government Health Scheme — protocols & formulary.", True),
    ("rchiips.org", "IIPS — National Family Health Survey reports.", True),
    ("iipsindia.ac.in", "International Institute for Population Sciences — health demography.", True),
    ("abdm.gov.in", "Ayushman Bharat Digital Mission — health data standards.", True),
    ("nbe.edu.in", "National Board of Examinations — postgraduate medical standards.", True),
    ("indiannursingcouncil.org", "Indian Nursing Council — nursing practice standards.", True),

    # ---------------- Band B — verify, then enable ----------------
    ("niv.co.in", "National Institute of Virology, Pune (ICMR) — virology reference.", False),
    ("nirt.res.in", "National Institute for Research in Tuberculosis (ICMR).", False),
    ("nirrch.res.in", "National Institute for Research in Reproductive & Child Health (ICMR).", False),
    ("nimr.org.in", "National Institute of Malaria Research (ICMR).", False),
    ("nicpr.res.in", "National Institute of Cancer Prevention & Research (ICMR).", False),
    ("nie.gov.in", "National Institute of Epidemiology (ICMR).", False),
    ("nariindia.org", "National AIDS Research Institute (ICMR).", False),
    ("rmrims.org.in", "Rajendra Memorial Research Institute of Medical Sciences (ICMR).", False),
    ("niohenv.res.in", "National Institute of Occupational Health (ICMR).", False),
    ("nirth.res.in", "National Institute of Research in Tribal Health (ICMR).", False),
    ("japi.org", "Journal of the Association of Physicians of India.", False),
    ("ijp-online.com", "Indian Journal of Pharmacology — IPS journal.", False),
    ("ijmm.org", "Indian Journal of Medical Microbiology — IAMM journal.", False),
    ("ijdvl.com", "Indian Journal of Dermatology, Venereology & Leprology.", False),
    ("ijo.in", "Indian Journal of Ophthalmology — AIOS journal.", False),
    ("ijccm.org", "Indian Journal of Critical Care Medicine — ISCCM journal.", False),
    ("ijem.in", "Indian Journal of Endocrinology & Metabolism.", False),
    ("ijaweb.org", "Indian Journal of Anaesthesia — ISA journal.", False),
    ("neurologyindia.com", "Neurology India — Neurological Society of India.", False),
    ("cancerjournal.net", "Journal of Cancer Research & Therapeutics.", False),
    ("indianjnephrol.org", "Indian Journal of Nephrology — ISN journal.", False),
    ("indianjpsychiatry.org", "Indian Journal of Psychiatry — IPS journal.", False),
    ("lungindia.com", "Lung India — Indian Chest Society journal.", False),
    ("jpgmonline.com", "Journal of Postgraduate Medicine — KEM Hospital, Mumbai.", False),
    ("jcdr.net", "Journal of Clinical & Diagnostic Research.", False),
    ("ijri.org", "Indian Journal of Radiology & Imaging — IRIA journal.", False),
    ("ijcm.org.in", "Indian Journal of Community Medicine — IAPSM journal.", False),
    ("jfmpc.com", "Journal of Family Medicine & Primary Care.", False),
    ("ijpmonline.org", "Indian Journal of Pathology & Microbiology.", False),
    ("jogi.co.in", "Journal of Obstetrics & Gynaecology of India — FOGSI.", False),
    ("ijhg.com", "Indian Journal of Human Genetics.", False),
    ("jgid.org", "Journal of Global Infectious Diseases.", False),
    ("ijstd.org", "Indian Journal of Sexually Transmitted Diseases & AIDS.", False),
    ("e-ijd.org", "Indian Journal of Dermatology.", False),
    ("ijmpo.org", "Indian Journal of Medical & Paediatric Oncology.", False),
    ("jpn.co.in", "Journal of Pediatric Neurosciences.", False),
    ("iapindia.org", "Indian Academy of Pediatrics — immunisation schedule & guidelines.", False),
    ("csi.org.in", "Cardiological Society of India — consensus statements.", False),
    ("rssdi.in", "RSSDI — diabetes guidelines (consensus, not statutory).", False),
    ("apiindia.org", "Association of Physicians of India — internal medicine guidance.", False),
    ("fogsi.org", "FOGSI — obstetric & gynaecological good practice recommendations.", False),
    ("isnindia.org", "Indian Society of Nephrology — specialty guidance.", False),
    ("indianchestsociety.org", "Indian Chest Society — respiratory consensus guidelines.", False),
    ("isccm.org", "Indian Society of Critical Care Medicine — ICU guidelines.", False),
    ("isaweb.in", "Indian Society of Anaesthesiologists — perioperative guidance.", False),
    ("iria.org.in", "Indian Radiological & Imaging Association — imaging standards.", False),
    ("asiindia.org", "Association of Surgeons of India — surgical guidance.", False),
    ("indianpsychiatricsociety.org", "Indian Psychiatric Society — clinical practice guidelines.", False),
    ("iansindia.org", "Indian Academy of Neurology — consensus guidance.", False),
    ("isgindia.org", "Indian Society of Gastroenterology — GI practice guidance.", False),
    ("inasl.org.in", "INASL — hepatology consensus statements.", False),
    ("iadvl.org", "IADVL — dermatology practice guidance.", False),
    ("aios.org", "All India Ophthalmological Society.", False),
    ("ioaindia.org", "Indian Orthopaedic Association.", False),
    ("usiindia.org", "Urological Society of India.", False),
    ("endocrinesocietyindia.org", "Endocrine Society of India — consensus statements.", False),
    ("nsi.org.in", "Neurological Society of India.", False),
    ("dciindia.gov.in", "Dental Council of India.", False),
    ("censusindia.gov.in", "Registrar General — Sample Registration System vital statistics.", False),
    ("ipc.gov.in", "Indian Pharmacopoeia Commission — alternate host.", False),

    # ---------------- Band C — unvetted: state health departments ----------------
    ("hmfw.ap.gov.in", f"Andhra Pradesh — {STATE_NOTE}", False),
    ("health.arunachal.gov.in", f"Arunachal Pradesh — {STATE_NOTE}", False),
    ("nhm.assam.gov.in", f"Assam — {STATE_NOTE}", False),
    ("shsb.bihar.gov.in", f"Bihar — {STATE_NOTE}", False),
    ("cghealth.nic.in", f"Chhattisgarh — {STATE_NOTE}", False),
    ("health.goa.gov.in", f"Goa — {STATE_NOTE}", False),
    ("gujhealth.gujarat.gov.in", f"Gujarat — {STATE_NOTE}", False),
    ("haryanahealth.nic.in", f"Haryana — {STATE_NOTE}", False),
    ("nrhmhp.gov.in", f"Himachal Pradesh — {STATE_NOTE}", False),
    ("jrhms.jharkhand.gov.in", f"Jharkhand — {STATE_NOTE}", False),
    ("karunadu.karnataka.gov.in", f"Karnataka — {STATE_NOTE}", False),
    ("dhs.kerala.gov.in", f"Kerala — {STATE_NOTE}", False),
    ("arogyakeralam.gov.in", f"Kerala (NHM) — {STATE_NOTE}", False),
    ("health.mp.gov.in", f"Madhya Pradesh — {STATE_NOTE}", False),
    ("arogya.maharashtra.gov.in", f"Maharashtra — {STATE_NOTE}", False),
    ("manipurhealthdirectorate.mn.gov.in", f"Manipur — {STATE_NOTE}", False),
    ("meghealth.gov.in", f"Meghalaya — {STATE_NOTE}", False),
    ("health.mizoram.gov.in", f"Mizoram — {STATE_NOTE}", False),
    ("nagahealth.nagaland.gov.in", f"Nagaland — {STATE_NOTE}", False),
    ("health.odisha.gov.in", f"Odisha — {STATE_NOTE}", False),
    ("nhm.punjab.gov.in", f"Punjab — {STATE_NOTE}", False),
    ("rajswasthya.nic.in", f"Rajasthan — {STATE_NOTE}", False),
    ("health.sikkim.gov.in", f"Sikkim — {STATE_NOTE}", False),
    ("tnhealth.tn.gov.in", f"Tamil Nadu — {STATE_NOTE}", False),
    ("hmfw.telangana.gov.in", f"Telangana — {STATE_NOTE}", False),
    ("health.tripura.gov.in", f"Tripura — {STATE_NOTE}", False),
    ("upnrhm.gov.in", f"Uttar Pradesh — {STATE_NOTE}", False),
    ("health.uk.gov.in", f"Uttarakhand — {STATE_NOTE}", False),
    ("wbhealth.gov.in", f"West Bengal — {STATE_NOTE}", False),
    ("health.delhi.gov.in", f"Delhi — {STATE_NOTE}", False),

    # ---------------- Band C — institutional protocols ----------------
    ("aiims.edu", f"AIIMS New Delhi — {INST_NOTE}", False),
    ("pgimer.edu.in", f"PGIMER Chandigarh — {INST_NOTE}", False),
    ("cmch-vellore.edu", f"CMC Vellore — {INST_NOTE}", False),
    ("sctimst.ac.in", f"SCTIMST Trivandrum — {INST_NOTE}", False),
    ("tmc.gov.in", f"Tata Memorial Centre — {INST_NOTE}", False),
    ("actrec.gov.in", f"ACTREC, Tata Memorial — {INST_NOTE}", False),
    ("nimhans.ac.in", f"NIMHANS Bengaluru — {INST_NOTE}", False),
    ("jipmer.edu.in", f"JIPMER Puducherry — {INST_NOTE}", False),
    ("sgpgi.ac.in", f"SGPGI Lucknow — {INST_NOTE}", False),
    ("rgcirc.org", f"Rajiv Gandhi Cancer Institute — {INST_NOTE}", False),
    ("aiimsbhopal.edu.in", f"AIIMS Bhopal — {INST_NOTE}", False),
    ("aiimsjodhpur.edu.in", f"AIIMS Jodhpur — {INST_NOTE}", False),
    ("aiimsbhubaneswar.nic.in", f"AIIMS Bhubaneswar — {INST_NOTE}", False),
    ("aiimsrishikesh.edu.in", f"AIIMS Rishikesh — {INST_NOTE}", False),
    ("aiimspatna.edu.in", f"AIIMS Patna — {INST_NOTE}", False),
    ("aiimsraipur.edu.in", f"AIIMS Raipur — {INST_NOTE}", False),
    ("aiimsnagpur.edu.in", f"AIIMS Nagpur — {INST_NOTE}", False),
    ("kgmu.org", f"King George's Medical University, Lucknow — {INST_NOTE}", False),
    ("bhu.ac.in", f"IMS-BHU Varanasi — {INST_NOTE}", False),
    ("maulanaazadmedicalcollege.in", f"Maulana Azad Medical College — {INST_NOTE}", False),
    ("grantmedicalcollege.org", f"Grant Medical College, Mumbai — {INST_NOTE}", False),
    ("mgims.ac.in", f"MGIMS Sevagram — {INST_NOTE}", False),
    ("stjohns.in", f"St John's Medical College, Bengaluru — {INST_NOTE}", False),
    ("kasturbahospital.org", f"Kasturba Medical College, Manipal — {INST_NOTE}", False),
    ("amrita.edu", f"Amrita Institute of Medical Sciences — {INST_NOTE}", False),

    # ---------------- Band C — further societies & bodies ----------------
    ("nbtc.naco.gov.in", "National Blood Transfusion Council.", False),
    ("pcindia.org", "Poison Control network (verify).", False),
    ("ipsindia.org", "Indian Pharmacological Society.", False),
    ("iapsmindia.org", "Indian Association of Preventive & Social Medicine.", False),
    ("iamrindia.org", "Indian Association of Medical Microbiologists.", False),
    ("ihsindia.org", "Indian Headache Society.", False),
    ("rheumatologyindia.org", "Indian Rheumatology Association.", False),
    ("ihsociety.org", "Indian Hepatology / related society.", False),
    ("apiindia-journal.org", "API journal properties.", False),
    ("icogonline.org", "Indian College of Obstetricians & Gynaecologists.", False),
    ("nnfi.org", "National Neonatology Forum of India.", False),
    ("iapneocon.org", "IAP Neonatology chapter.", False),
    ("pediatriconcall.com", "Paediatric clinical reference (commercial — review carefully).", False),
    ("ipsn.org.in", "Indian Paediatric Nephrology group.", False),
    ("isham-india.org", "Indian medical mycology society.", False),
    ("tsi-india.org", "Transplantation Society of India.", False),
    ("issindia.org", "Indian Society of Surgeons / related.", False),
    ("vsi-india.org", "Vascular Society of India.", False),
    ("cardiologysocietyindia.org", "Cardiology society alternate host.", False),
    ("iheartindia.org", "Cardiac society (verify).", False),
    ("isvsindia.org", "Indian Society for Vascular Surgery.", False),
    ("iabsindia.org", "Indian Association of Biomedical Scientists.", False),
    ("acbindia.org", "Association of Clinical Biochemists of India.", False),
    ("ismrindia.org", "Indian Society for Magnetic Resonance.", False),
    ("aroi.org", "Association of Radiation Oncologists of India.", False),
    ("ismpoindia.org", "Indian Society of Medical & Paediatric Oncology.", False),
    ("ihcs.org.in", "Indian Haematology / cancer society.", False),
    ("isdindia.org", "Indian Society of Diabetology.", False),
    ("esiendocrine.org", "Endocrine society alternate host.", False),
    ("iosindia.org", "Indian Osteoporosis Society.", False),
    ("igsindia.org", "Indian Geriatrics Society.", False),
    ("ipaindia.org", "Indian Psychiatric / palliative association (verify which).", False),
    ("palliativecare.in", "Indian Association of Palliative Care.", False),
    ("painsocietyindia.org", "Indian Society for Study of Pain.", False),
    ("sleepindia.org", "Indian Society for Sleep Research.", False),
    ("epilepsyindia.org", "Indian Epilepsy Society.", False),
    ("strokeindia.org", "Indian Stroke Association.", False),
    ("mnjinstitute.org", "MNJ Institute of Oncology, Hyderabad.", False),
    ("cancerindia.org.in", "Indian Cancer Society.", False),
    ("tbassociation.org", "Tuberculosis Association of India.", False),
    ("lepraindia.org", "Leprosy programme / association.", False),

    # ---------------- AYUSH — out of MVP scope, keep disabled ----------------
    ("ayush.gov.in", "Ministry of Ayush — OUT OF SCOPE: corpus is modern/allopathic only. Enable only if a labelled AYUSH mode ships.", False),
    ("ccras.nic.in", "Central Council for Research in Ayurvedic Sciences — OUT OF SCOPE, same exclusion as ayush.gov.in.", False),
    ("ccrhindia.nic.in", "Central Council for Research in Homoeopathy — OUT OF SCOPE, same exclusion as ayush.gov.in.", False),
]

# Entry 157 in the source list, "aiims.edu/aiims/departments/poison", is a page
# path rather than a domain; allowed_domains takes hosts only, and aiims.edu is
# already present above, so it is intentionally not repeated here.
